# Generated by Django 2.2.19 on 2022-05-20 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'default_related_name': 'follows', 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
