# Generated by Django 2.2.19 on 2022-05-24 17:39

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220520_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favourite',
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_favourited',
            field=models.BooleanField(default=False, verbose_name='В избранном'),
        ),
    ]
