# Generated by Django 2.2.19 on 2022-05-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220524_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='is_favourited',
            new_name='is_favourite',
        ),
    ]
