# Generated by Django 2.2.19 on 2022-05-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220524_2041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
