# Generated by Django 2.2.19 on 2022-05-28 14:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0007_auto_20220525_2111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourite',
            new_name='Favorite',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='favourite_recipe',
            new_name='favorite_recipe',
        ),
    ]
